export const errorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  AI_CONFIGURATION_ERROR: 'AI_CONFIGURATION_ERROR',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
};
